Add final touches
Baayeh/bookstore pull request #5
Opened 2022-11-08 17:28 UTC by Baayeh

- Added some styling

2022-11-08 18:17 UTC, Whoistolu requested changes
Hi @Baayeh 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-08 18:17 UTC, Whoistolu commented on src/components/AddBook.jsx
>            />
- [ ] [REQUIRED] For this field where a book gets added, you need to follow the exact styles as used in the zeplin design. Kindly change the font, color, font weight, and every other property the (Add new book, book title, category, add book button) has.
### Your Design
<img width="1440" alt="Screenshot 2022-11-08 at 18 45 56" src="https://user-images.githubusercontent.com/58692590/200640636-6314b9b9-795f-4937-9eaf-42c485cb80ca.png">

### Zeplin Design
<img width="1019" alt="Screenshot 2022-11-08 at 18 59 48" src="https://user-images.githubusercontent.com/58692590/200640972-5c7b4984-7150-4a64-9476-4498b9c98b63.png">

If you click on the `ADD NEW BOOK` for example, you will get a property of it on the right side of your screen. Kindly apply these properties for every content of your design.
### For example
<img width="1440" alt="Screenshot 2022-11-08 at 19 01 45" src="https://user-images.githubusercontent.com/58692590/200641588-cceb9307-1b25-463d-93ef-6c70e1803f1f.png">

2022-11-08 18:17 UTC, Whoistolu commented on src/components/Book.jsx
> +          </button>
- [ ] REQUIRED] The button (comments, remove, edit) also needs to follow the exact styles as used in the zeplin design. Kindly change the font, color, font weight, and every property they have on zeplin.
- [ ] [REQUIRED] Kindly apply the same to the other h-tags (Fiction, dfsdf, sdfsdfsd, chapter 3, current chapter), update-progress-button.

### Your design
<img width="1440" alt="Screenshot 2022-11-08 at 18 45 20" src="https://user-images.githubusercontent.com/58692590/200642496-e1b6777c-13b1-4f32-aeb8-c0b7ceb97d55.png">

### Zeplin Design
<img width="1020" alt="Screenshot 2022-11-08 at 19 14 21" src="https://user-images.githubusercontent.com/58692590/200643509-1a4de402-b06b-4d6c-9265-40ee2559b262.png">

2022-11-09 09:02 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @Baayeh,

✔️ Nice styling

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-09 09:04 UTC, merged